name: space-debris
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - jupyter
  - scikit-learn
  - pip
  - pip:
    - spacetrack
    - skyfield
    - astropy